// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTos-7erf9d4vvr5yu6cnLHSbVO-It5w',
    appId: '1:961746104379:web:7e573bce5555d2ba7f2c1e',
    messagingSenderId: '961746104379',
    projectId: 'stream-app-eb6c3',
    authDomain: 'stream-app-eb6c3.firebaseapp.com',
    storageBucket: 'stream-app-eb6c3.appspot.com',
    measurementId: 'G-9WW7SZK249',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEuo_UdjixwdH1HRK9KY2yy3QFejz0eEE',
    appId: '1:961746104379:android:cd47e24b39786c987f2c1e',
    messagingSenderId: '961746104379',
    projectId: 'stream-app-eb6c3',
    storageBucket: 'stream-app-eb6c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ39ddaEZdulfeNTnbLbjJShRQHCOq60E',
    appId: '1:961746104379:ios:cebae5feb24a18bc7f2c1e',
    messagingSenderId: '961746104379',
    projectId: 'stream-app-eb6c3',
    storageBucket: 'stream-app-eb6c3.appspot.com',
    iosBundleId: 'com.example.streamUp',
  );
}
